### ISSUE TITLE
Add Trino Operator

### ISSUE THREAD

**Issue by mykidong** [cloudcheflabs/dataroaster#1]
Trino operator will be used to create / update / delete trino clusters.
In addition to that, It should also monitor trino clusters and sometimes replace the exhausted trino workers with the new ones if detected.
We can also consider support of graceful shutdown when there are existing queries being executed which have to be executed before trino cluster shutdown.

**Comment by cloudcheflabs** [comment]
Trino operator added with the following functionalities:
- create trino clusters with custom resource.
- delete trino clusters with custom resource.
