### ISSUE TITLE
Add Trino Gateway to proxy trino clusters.

### ISSUE THREAD

**Issue by mykidong** [cloudcheflabs/dataroaster#2]
Trino can be used for the cases of  ETL, interactive(adhoc) and scheduled, etc. 
We can create trino clusters for these usages individually. In order to load-balance trino clusters, and to support trino coordinator HA, trino gateway should be used. We can extend this concept to trino ecosystem.

Trino ecosystem consists of trino gateway, authenticator, admin and trino clusters, etc.
We can think of the following scenario which can happen in trino ecosystem.
- clients(applications, redash, tableau, cli, etc) will request queries to trino gateway.
- trino gateway will filter parameters of request to authenticate / authorize user with authenticator.
- the queries requested will be routed dynamically to the downstream trino cluster for the individual usages of ETL, interactive, scheduled.
- admin will create / update / delete trino clusters on kubernetes using [trino operator](https://github.com/cloudcheflabs/dataroaster/issues/1).
- admin will register / deregister / activate / deactivate trino cluster to trino gateway.

**Comment by cloudcheflabs** [comment]
https://github.com/cloudcheflabs/dataroaster/pull/6
