### ISSUE TITLE
where is spark-thrift-server-4.8.0-SNAPSHOT-spark-job.jar

### ISSUE THREAD

**Issue by weijiasheng** [cloudcheflabs/dataroaster#40]
hello，I want to try tun the spark demo，but cannot download spark-thrift-server-4.8.0-SNAPSHOT-spark-job.jar？ where is can be download ，thanks？

**Comment by cloudcheflabs** [comment]
Hi,
You can build your spark thrift server uberjar with cloning dataroaster sources.
```
git clone https://github.com/cloudcheflabs/dataroaster.git;
cd dataroaster;
mvn -e -DskipTests=true clean install;
cd components/hive/spark-thrift-server;
mvn -e -DskipTests=true clean install shade:shade;
ls -al target
```
After packaging spark thrift server, you need to upload spark thrift server uberjar on your s3 bucket.
If you want to run spark thrift server using spark operator, it may be helpful for you to see the blog https://itnext.io/hive-on-spark-with-spark-operator-9a43ea7ebe06 

Regards,
- Kidong.
