### ISSUE TITLE
whereis the spark dockerfile

### ISSUE THREAD

**Issue by weijiasheng** [cloudcheflabs/dataroaster#41]
hello，where is the spark3 dockerfile，like cloudcheflabs/spark:v3.4.0 ，thanks！

**Comment by cloudcheflabs** [comment]
You need to build spark docker image for yourself. See the following instructions:

- build spark: https://spark.apache.org/docs/latest/building-spark.html
- build spark docker image: https://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images

You can also consult my blog post: https://itnext.io/things-to-consider-to-submit-spark-jobs-on-kubernetes-766402c21716
